### ISSUE TITLE
Incomplete instructions in the tutorials.

### ISSUE THREAD

**Issue by martonklecska** [canonical/microstack.run#210]
## Summary

The following is missing from Step 4-5:
`multipass exec microstack-vm -- `

## Process

> Install MicroStack
> 
> multipass exec microstack-vm -- sudo snap install microstack --beta
> 
> Set up MicroStack
> 
> sudo microstack init --auto --control
> 
> Launch a VM
> 
> microstack launch cirros --name test
> 
> 

## Current and expected result

Snap does not exist for macOS. 
I was not expecting a snap command to be issued on a mac terminal in the tutorial.

## Screenshot

n/a

## Browser details

n/a

**Comment by sowasred2012** [comment]
@evilnick is this something you can help us with?

**Comment by pmatulis** [comment]
@martonklecska Please provide a link to the tutorials in question.

**Comment by evilnick** [comment]
@pmatulis is the guy for this stuff :)

**Comment by carkod** [comment]
Stale
