### ISSUE TITLE
Dead link "Get free OpenStack e-book"

### ISSUE THREAD

**Issue by setharnold** [canonical/microstack.run#229]
Hello, https://microstack.run/ has a green "button" link:

[Get free OpenStack e-book](https://ubuntu.com/engage/openstack-ebook)

This link currently gives me a 404.

Thanks

**Comment by sparkiegeek** [comment]
It links to https://ubuntu.com/engage/openstack-ebook which is the 404

**Comment by carkod** [comment]
This is fixed now by https://github.com/canonical/ubuntu.com/commit/e09e8e95451ea1db08187a739ec5240c91631140
