### ISSUE TITLE
404 page missing on canonical openstack ebook

### ISSUE THREAD

**Issue by mthibaut** [canonical/microstack.run#230]
Hi,

Site https://microstack.run/ directly links to https://ubuntu.com/engage/openstack-ebook which results in a 404 not found error.

---
*Reported from: https://ubuntu.com/engage/openstack-ebook*

**Comment by pmatulis** [comment]
This is fixed now by https://github.com/canonical/ubuntu.com/commit/e09e8e95451ea1db08187a739ec5240c91631140
