### ISSUE TITLE
The top level `Contribute` link points to a 404 page on GitHub.

### ISSUE THREAD

**Issue by fnordahl** [canonical/microstack.run#253]
## Summary

The top level `Contribute` link points to a 404 page on GitHub.

## Process

1. Go to microstack.run.
2. Click `Contribute`

## Current and expected result

I expected to be forwarded to the active GitHub repository for the `openstack` (which presumably is https://github.com/canonical/snap-openstack), but instead I'm forwarded to a 404 page representing a previous location.

**Comment by pmatulis** [comment]
This has been reported in #251.
