### ISSUE TITLE
Change to requests broke dotrun

### ISSUE THREAD

**Issue by cjohnston1158** [canonical/microstack.run#259]
## Summary

Error while fetching server API version: Not supported URL scheme http+docker
Dotrun needs Docker to work, please check if Docker is installed and running

[Example](https://github.com/canonical/microstack.run/actions/runs/9212477259/job/25344179033?pr=258)

Upstream:
[Requests 2.32.0 Not supported URL scheme http+docker](https://github.com/psf/requests/issues/6707)

**Comment by carkod** [comment]
Looks like everything is working now.
